/**
 * Tenant scaffolding — materialize the full directory tree for a new tenant.
 *
 * Given a validated TenantConfig, creates:
 *   tenants/<id>/
 *     tenant.json
 *     procedures/
 *     agents/
 *     audit/
 *     state/
 *     dashboard/
 *     .secrets/     (empty, for OS keychain pointers)
 *     registry/
 *       agents.json
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { TenantConfig } from './types.js';

// ---------------------------------------------------------------------------
// Directory layout
// ---------------------------------------------------------------------------

/**
 * Standard subdirectories under tenants/<id>/.
 * Order matters: parents before children.
 */
const TENANT_SUBDIRS = [
  'procedures',
  'agents',
  'audit',
  'state',
  'dashboard',
  '.secrets',
  'registry',
  'identity',
  'memory',
] as const;

export type TenantSubdir = (typeof TENANT_SUBDIRS)[number];

export interface ScaffoldResult {
  tenant_id: string;
  root: string;
  created: string[];   // paths that were newly created
  skipped: string[];   // paths that already existed (idempotent)
}

// ---------------------------------------------------------------------------
// Main scaffold function
// ---------------------------------------------------------------------------

/**
 * Materialize the directory tree for a tenant.
 *
 * @param config   Validated TenantConfig (from validateTenantConfig)
 * @param baseDir  Parent directory — defaults to `<cwd>/tenants`
 *                 Override in tests to isolate from real tenant dirs.
 * @param force    If true, overwrite tenant.json even if it exists.
 */
export function scaffoldTenant(
  config: TenantConfig,
  baseDir: string,
  force = false,
): ScaffoldResult {
  const root = join(baseDir, config.tenant_id);
  const created: string[] = [];
  const skipped: string[] = [];

  // Helper: mkdir -p with tracking
  const ensureDir = (dir: string) => {
    if (existsSync(dir)) {
      skipped.push(dir);
    } else {
      mkdirSync(dir, { recursive: true });
      created.push(dir);
    }
  };

  // Helper: write file with tracking
  const ensureFile = (path: string, content: string, overwrite = false) => {
    if (existsSync(path) && !overwrite) {
      skipped.push(path);
    } else {
      writeFileSync(path, content, { encoding: 'utf-8' });
      created.push(path);
    }
  };

  // Create root + subdirs
  ensureDir(root);
  for (const sub of TENANT_SUBDIRS) {
    ensureDir(join(root, sub));
  }

  // Write tenant.json
  const tenantJsonPath = join(root, 'tenant.json');
  ensureFile(tenantJsonPath, JSON.stringify(config, null, 2) + '\n', force);

  // Write registry/agents.json stub
  const agentsPath = join(root, 'registry', 'agents.json');
  ensureFile(agentsPath, JSON.stringify([], null, 2) + '\n');

  // Write identity/.gitkeep and audit/.gitkeep (so dirs survive git add)
  for (const sub of ['identity', 'audit', 'state', 'dashboard', '.secrets'] as const) {
    ensureFile(join(root, sub, '.gitkeep'), '');
  }

  // Write procedures/.gitkeep
  ensureFile(join(root, 'procedures', '.gitkeep'), '');

  // Write a starter README for the tenant
  const readmePath = join(root, 'README.md');
  ensureFile(
    readmePath,
    `# ${config.name} (${config.tenant_id})\n\nGenerated by Penelope v${config.schema_version}.\n\n` +
    `Vertical: \`${config.vertical}\`\n\n` +
    `## Directory layout\n\n` +
    `- \`tenant.json\` — business config (edit to reconfigure)\n` +
    `- \`procedures/\` — YAML procedure files loaded by agents at spawn\n` +
    `- \`agents/\` — per-agent persona files\n` +
    `- \`audit/\` — append-only audit log\n` +
    `- \`state/\` — runtime state (SQLite bus, caches)\n` +
    `- \`dashboard/\` — per-tenant owner app\n` +
    `- \`.secrets/\` — OS keychain pointers (never commit secrets here)\n` +
    `- \`registry/agents.json\` — registered agent list\n`,
  );

  return { tenant_id: config.tenant_id, root, created, skipped };
}

/**
 * Return the expected path to a tenant's tenant.json.
 */
export function tenantConfigPath(baseDir: string, tenantId: string): string {
  return join(baseDir, tenantId, 'tenant.json');
}

/**
 * Return the expected path to a tenant's procedures directory.
 */
export function tenantProceduresDir(baseDir: string, tenantId: string): string {
  return join(baseDir, tenantId, 'procedures');
}
